In [2]:
#IMPORTAR LAS BIBLIOTECAS
import pandas as pd
import numpy as np
import scipy
from math import sqrt
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#Metricas 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#Calibracion
from sklearn.calibration import calibration_curve
from sklearn.datasets import make_classification
from sklearn.calibration import CalibratedClassifierCV

#Cross validation
from sklearn.model_selection import train_test_split

In [7]:
##Cargar los datos del csv
rawData = pd.read_csv('nuevo.csv', header=0)

In [8]:
##Revisar la estructura de los datos
rawData.head()

Unnamed: 0  ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  \
0           0   1      20000    2          2         1   24      2      2   
1           1   2     120000    2          2         2   26     -1      2   
2           2   3      90000    2          2         2   34      0      0   
3           3   4      50000    2          2         1   37      0      0   
4           4   5      50000    1          2         1   57     -1      0   

   PAY_3  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0     -1  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4     -1  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default_payment_next_month  
0         0         0         0                         NaN  
1      1000         0      2000                         NaN  
2      1000      1000      5000                         NaN  
3      1100      1069      1000                         NaN  
4      9000       689       679                         NaN  

[5 rows x 26 columns]

In [9]:
##Verificar los tipos de datos
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 26 columns):
Unnamed: 0                    30000 non-null int64
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
SEX                           30000 non-null int64
EDUCATION                     30000 non-null int64
MARRIAGE                      30000 non-null int64
AGE                           30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5               

In [23]:
#features
features = rawData.iloc[:,12:23]
print('Resumen de caracteristicas de los datos')
features.head()


Summary of feature sample


BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0       3913       3102        689          0          0          0         0   
1       2682       1725       2682       3272       3455       3261         0   
2      29239      14027      13559      14331      14948      15549      1518   
3      46990      48233      49291      28314      28959      29547      2000   
4       8617       5670      35835      20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  
0       689         0         0         0  
1      1000      1000      1000         0  
2      1500      1000      1000      1000  
3      2019      1200      1100      1069  
4     36681     10000      9000       689

In [24]:
######Definir la variable dependiente
depVar = rawData['PAY_AMT6']
print (depVar)

0           0
1        2000
2        5000
3        1000
4         679
         ... 
29995    1000
29996       0
29997    3100
29998    1804
29999    1000
Name: PAY_AMT6, Length: 30000, dtype: int64


In [25]:
##Regresion: Establecemos el conjunto de entrenamiento para la variable x y entrenamiento
##seleccionamos 1000 caracteristicas

#Entrenamiento
X_train = (features[: 1000])  
X_train.head()
#Dependent Variable Training Set (y Training)
y_train = depVar[: 1000]
y_train_count = len(y_train.index)
print('The number of observations in the Y training set are:',str(y_train_count))
y_train.head()

The number of observations in the Y training set are: 1000


0       0
1    2000
2    5000
3    1000
4     679
Name: PAY_AMT6, dtype: int64

In [27]:
# Conjunto de prueba (Prueba X) 
X_test = features[-100:] 
X_test_count = len(X_test.index) 
print ('El número de observaciones en el conjunto de prueba de características es:', str (X_test_count)) 
print (X_test.head())


El número de observaciones en el conjunto de prueba de características es: 100
       BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
29900      16809          0          0          0          0          0   
29901      50845      48750     103486      50590      50248      49387   
29902      10392     168088     168955     161351     126198     124746   
29903      27378      17082      13333         99         99     172104   
29904      54952      56021      54126      58732      59306      59728   

       PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  
29900         0         0         0         0         0  
29901         0      6556      3250      1563      1208  
29902    168096      6409      7335      4448      4519  
29903     10018     13333        99        99    172104  
29904      2600      4553      5800      2000      1000  


In [28]:
##Regression : Establecer la verdad
#Ground Truth (y_test)  
y_test = depVar[-100:] 
y_test_count = len(y_test.index) 
print ('El número de observaciones en el conjunto de entrenamiento Y son:', str(y_test_count)) 
y_test.head ()

El número de observaciones en el conjunto de entrenamiento Y son: 100


29900        0
29901      781
29902     5003
29903    30013
29904     1462
Name: PAY_AMT6, dtype: int64

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)
X_train.shape, X_test.shape

((750, 11), (250, 11))

In [30]:
###Creacion de modelos de regresion
#Models
modelSVR = SVR()
modelRF = RandomForestRegressor()
modelLR = LinearRegression()

In [31]:
modelRF.fit(X_train,y_train)
modelRF.fit(X_train,y_train)
modelSVR.fit(X_train,y_train)
modelLR.fit(X_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
##Regression: Scoring
print(cross_val_score(modelRF, X_train, y_train)) 
modelRF.score(X_train,y_train)

[ 0.01627163 -0.25015934  0.22526334]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.801137163797379

In [33]:
print(cross_val_score(modelSVR, X_train, y_train)) 
modelSVR.score(X_train,y_train)

[-0.02064551 -0.02933917 -0.04249092]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto'

-0.024559818049274096

In [34]:
print(cross_val_score(modelLR, X_train, y_train)) 
modelLR.score(X_train,y_train)

[ 0.34770524  0.01953414 -0.39865136]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.6293495662053554